In [1]:
#pip install outlier_utils

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
from outliers import smirnov_grubbs as grubbs

In [3]:
# Example Data 생성

data=np.array([5,14,15,15,14,19,17,16,20,22,8,21,28,11,9,29,40])


In [4]:
#Two-Sided Grubb's Test

grubbs.test(data, alpha=.05)

# outlier 였던 40이 제거됨

array([ 5, 14, 15, 15, 14, 19, 17, 16, 20, 22,  8, 21, 28, 11,  9, 29])

In [5]:
# One-Sided Grubb's Test

#define data
data = np.array([5, 14, 15, 15, 14, 19, 17, 16, 20, 22, 8, 21, 28, 11, 9, 29, 40])

#perform Grubbs' test to see if minimum value is an outlier
grubbs.min_test(data, alpha=.05)

# 결국, min 값 중 outlier 값으로 판명한 게 없음.

array([ 5, 14, 15, 15, 14, 19, 17, 16, 20, 22,  8, 21, 28, 11,  9, 29, 40])

In [6]:
grubbs.max_test(data, alpha=.05)

# 역시나 40을 outlier 값으로 판명.

array([ 5, 14, 15, 15, 14, 19, 17, 16, 20, 22,  8, 21, 28, 11,  9, 29])

In [7]:
# Extract the Value of the Outlier

#define data
data = np.array([5, 14, 15, 15, 14, 19, 17, 16, 20, 22, 8, 21, 28, 11, 9, 29, 40])

# Grubb test 후 outlier 값 확인
grubbs.max_test_outliers(data, alpha=.05)

[40]

In [8]:
#Extract the Index of the Outlier

#define data
data = np.array([5, 14, 15, 15, 14, 19, 17, 16, 20, 22, 8, 21, 28, 11, 9, 29, 40])

# Grubb test 후 outlier 값 인덱스 확인
grubbs.max_test_indices(data, alpha=.05)

[16]